### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by swapnil002** [chilts/node-coupon-code#7]
Is the coupon code generated unique?

**Comment by chilts** [comment]
I have no guarantees that the coupon will be unique, however, there should be sufficiently many possibilities that you'll be okay unless you're generating millions and billions of them.

Anyway, ascertaining that each one is unique should be the work of your database or datastore. If inserting into the database, you'll want a unique constraint on that column to make sure each is unique. If the store fails due to a copy being inserted, then you'll have to re-generate and try again.
